CREATE DATABASE AutoAlert;

USE AutoAlert;

CREATE TABLE usuarios (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    senha VARCHAR(255) NOT NULL,
    ativo TINYINT(1) NOT NULL DEFAULT 1,
    criado_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    alterado_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE USER 'AccessSystemAutoAlert'@'%' IDENTIFIED BY 'SystemAccessAutoAlert';

GRANT ALL PRIVILEGES ON autoalert.* TO 'AccessSystemAutoAlert'@'%';

FLUSH PRIVILEGES;
